import type { CSSProperties, ReactNode } from 'react'

interface EmailShellProps {
  children: ReactNode
  ctaHref?: string
  ctaLabel?: string
  eyebrow?: string
  footer?: ReactNode
  previewText: string
  title: string
}

const bodyStyle: CSSProperties = {
  backgroundColor: '#f8fafc',
  color: '#0f172a',
  fontFamily:
    "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  margin: 0,
  padding: '32px 16px',
}

const containerStyle: CSSProperties = {
  backgroundColor: '#ffffff',
  border: '1px solid #e2e8f0',
  borderRadius: '24px',
  margin: '0 auto',
  maxWidth: '640px',
  overflow: 'hidden',
  width: '100%',
}

const sectionStyle: CSSProperties = {
  padding: '32px',
}

const eyebrowStyle: CSSProperties = {
  color: '#4f46e5',
  fontSize: '12px',
  fontWeight: 700,
  letterSpacing: '0.12em',
  margin: '0 0 12px',
  textTransform: 'uppercase',
}

const titleStyle: CSSProperties = {
  color: '#0f172a',
  fontSize: '28px',
  fontWeight: 700,
  lineHeight: 1.2,
  margin: 0,
}

const contentStyle: CSSProperties = {
  color: '#334155',
  fontSize: '15px',
  lineHeight: 1.7,
  marginTop: '20px',
}

const buttonStyle: CSSProperties = {
  backgroundColor: '#111827',
  borderRadius: '999px',
  color: '#ffffff',
  display: 'inline-block',
  fontSize: '14px',
  fontWeight: 700,
  marginTop: '24px',
  padding: '14px 22px',
  textDecoration: 'none',
}

const footerStyle: CSSProperties = {
  borderTop: '1px solid #e2e8f0',
  color: '#64748b',
  fontSize: '13px',
  lineHeight: 1.6,
  padding: '20px 32px 28px',
}

const previewStyle: CSSProperties = {
  color: '#f8fafc',
  display: 'none',
  fontSize: '1px',
  lineHeight: '1px',
  maxHeight: 0,
  maxWidth: 0,
  opacity: 0,
  overflow: 'hidden',
}

export function EmailShell({
  children,
  ctaHref,
  ctaLabel,
  eyebrow = 'FormFlow',
  footer,
  previewText,
  title,
}: EmailShellProps) {
  return (
    <html lang="en">
      <body style={bodyStyle}>
        <div style={previewStyle}>{previewText}</div>
        <div style={containerStyle}>
          <section style={sectionStyle}>
            <p style={eyebrowStyle}>{eyebrow}</p>
            <h1 style={titleStyle}>{title}</h1>
            <div style={contentStyle}>{children}</div>
            {ctaHref && ctaLabel ? (
              <a href={ctaHref} rel="noreferrer" style={buttonStyle} target="_blank">
                {ctaLabel}
              </a>
            ) : null}
          </section>
          <footer style={footerStyle}>
            {footer ?? (
              <p style={{ margin: 0 }}>
                Sent by FormFlow. This message was generated by the development email service.
              </p>
            )}
          </footer>
        </div>
      </body>
    </html>
  )
}
